server:
  port: 18071
spring:
  application:
    name: instance-client
#conusl
  cloud:
    consul:
      host: localhost
      port: 18500
  #spring.datasource
  #数据库登陆用户名
  datasource:
    username: root
  #数据库登陆密码
    password: 9ymdSjflyI%g
  #数据库url
    url: jdbc:mysql://am-uf6w02i966dd03a79167320.ads.aliyuncs.com:3306/information_schema?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true
  #数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis
# 指定 mapper.xml 的位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
  type-aliases-package: com.chandler.*.domain
